services:
  rag-app:
    build: .
    container_name: rag-app
    ports:
      - "8800:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - hf_cache:/root/.cache/huggingface
    restart: unless-stopped

volumes:
  hf_cache:
